title: "Ivan Marevics Homepage"
email: "ivan_marevic@web.de"
author: Ivan Marevic
url: "" # the base hostname & protocol
baseurl: "" # subpath

sass:
  sass_dir: assets/css

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
